apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
  annotations:
    argocd.argoproj.io/sync-options: Validate=false  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
    storageclass: storage-low  